import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { createDebouncedLocalStorage } from './debounced-storage';
import { gaengeFuerPathArea } from './gang-aus-patharea';
import { generateConnectors } from './gang-insel-verbinder';
import {
  TopisState,
  TopisObject,
  Hall,
  Path,
  PathArea,
  Gang,
  FFZ,
  Conveyor,
  Tool,
  ObjectType,
  DEFAULT_HALL,
  DEFAULT_FFZ,
  OBJECT_DEFAULTS,
  ProjektSnapshot,
  MittlererWegRun,
  Verlader,
} from '@/types/topis';
import type { LayoutSnapshot } from '@/types/betriebsdaten';
import { findPathBetweenObjects, buildGangGraph, findPath, generateBasicGangNet } from './pathfinding';
import { findNearestWall, torBoxFromAnchor, rampeBoxFromAnchor, reanchorTore, deriveWalls } from './wall-anchor';
import type { GeneratedLayout } from './nl-layout';
import * as mengenActions from './mengen-store-actions';

// Modul-lokaler Debounce-Timer für Path-Auto-Recompute beim Object-Move
let _recomputeTimer: number | null = null;

// ==================== UNDO/REDO ====================
const MAX_UNDO_STACK = 50;

function captureLayoutSnapshot(state: TopisState): LayoutSnapshot {
  return {
    objects: structuredClone(state.objects),
    gaenge: structuredClone(state.gaenge),
    ffz: structuredClone(state.ffz),
    halls: structuredClone(state.halls),
    paths: structuredClone(state.paths),
    pathAreas: structuredClone(state.pathAreas),
    conveyors: structuredClone(state.conveyors),
  };
}

function restoreLayoutSnapshot(snapshot: LayoutSnapshot): Partial<TopisState> {
  return {
    objects: structuredClone(snapshot.objects),
    gaenge: structuredClone(snapshot.gaenge),
    ffz: structuredClone(snapshot.ffz),
    halls: structuredClone(snapshot.halls),
    paths: structuredClone(snapshot.paths ?? []),
    pathAreas: structuredClone(snapshot.pathAreas ?? []),
    conveyors: structuredClone(snapshot.conveyors ?? []),
    selectedObject: null,
    selectedPath: null,
    selectedGang: null,
    selectedPathArea: null,
    selectedConveyor: null,
  };
}

interface TopisStore extends TopisState {
  // Undo/Redo
  undoStack: LayoutSnapshot[];
  redoStack: LayoutSnapshot[];
  originalLayout: LayoutSnapshot | null;
  pushSnapshot: () => void;
  undo: () => void;
  redo: () => void;
  canUndo: () => boolean;
  canRedo: () => boolean;
  saveOriginalLayout: () => void;
  resetToOriginal: () => void;

  // Hall Actions
  setHalls: (halls: Hall[]) => void;
  setActiveHall: (id: number) => void;
  updateHall: (id: number, updates: Partial<Hall>) => void;
  rotateHall90: () => void;

  // Object Actions
  addObject: (obj: Omit<TopisObject, 'id'>) => TopisObject;
  addObjects: (objs: Omit<TopisObject, 'id'>[]) => TopisObject[];
  updateObject: (id: number, updates: Partial<TopisObject>) => void;
  deleteObject: (id: number) => void;
  selectObject: (obj: TopisObject | null) => void;

  // Path Actions
  addPath: (path: Omit<Path, 'id'>) => void;
  addPaths: (paths: Omit<Path, 'id'>[]) => void;
  updatePath: (id: number, updates: Partial<Path>) => void;
  deletePath: (id: number) => void;
  deleteAutoGeneratedPaths: () => void;
  selectPath: (path: Path | null) => void;

  // Gang Actions
  setGaenge: (gaenge: Gang[]) => void;
  addGang: (gang: Gang) => void;
  updateGang: (id: number, updates: Partial<Gang>) => void;
  deleteGang: (id: number) => void;
  selectGang: (gang: Gang | null) => void;
  toggleShowGaenge: () => void;

  // FFZ Actions
  setFFZ: (ffz: FFZ[]) => void;

  // PathArea Actions
  addPathArea: (area: Omit<PathArea, 'id'>) => PathArea;
  updatePathArea: (id: number, updates: Partial<PathArea>) => void;
  deletePathArea: (id: number) => void;
  selectPathArea: (area: PathArea | null) => void;

  // Mittlerer-Weg-Run Actions (Lastenheft 3.2.4)
  saveMittlererWegRun: (run: Omit<MittlererWegRun, 'id'>) => void;
  deleteMittlererWegRun: (id: number) => void;

  // Conveyor Actions
  addConveyor: (conveyor: Omit<Conveyor, 'id'>) => Conveyor;
  updateConveyor: (id: number, updates: Partial<Conveyor>) => void;
  deleteConveyor: (id: number) => void;
  selectConveyor: (conveyor: Conveyor | null) => void;

  // View Actions
  setZoom: (zoom: number) => void;
  setPan: (pan: { x: number; y: number }) => void;
  setTool: (tool: Tool) => void;
  toggleGrid: () => void;
  toggleSnap: () => void;
  // KI-Textbuilder (Zustand in TopisState; hier nur die Actions).
  setNlGhost: (g: GeneratedLayout | null) => void;
  setNlBuilderOpen: (open: boolean) => void;
  setCockpitRoute: (route: { startId: number; endId: number } | null) => void;

  // SimAuftrag-Actions (visuelles Auftrags-Anlegen im Canvas)
  startSimAuftrag: (vonObjectId: number) => void;
  cancelSimAuftrag: () => void;
  finishSimAuftrag: (nachObjectId: number, colli: number, notiz?: string) => void;
  updateSimAuftrag: (id: string, patch: Partial<Pick<import('@/types/topis').SimAuftrag, 'vonObjectId' | 'nachObjectId' | 'colli' | 'minProColliOverride' | 'notiz'>>) => void;
  removeSimAuftrag: (id: string) => void;
  clearSimAuftraege: () => void;
  /** Lädt eine vorgefertigte Liste von Beispiel-Aufträgen (für Demo-Zwecke) */
  seedBeispielAuftraege: () => number;
  /**
   * Forkt einen IST-Auftrag zu einer SIM-Variante (was-wäre-wenn).
   * Wenn der parent schon eine SIM hat, wird die alte ersetzt.
   */
  forkSimAuftragAsSim: (parentId: string, neuerNachObjectId: number, neueColli?: number) => void;
  /** Entfernt nur die SIM-Variante zu einem IST-Auftrag (parent bleibt). */
  removeSimVarianteFor: (parentId: string) => void;
  /** Setzt das fokussierte Tor für die Wege-Anzeige. null = nichts fokussiert. */
  setFocusedTor: (id: number | null) => void;
  /** Schaltet den Übersichts-Modus (alle Wege gleichzeitig) ein/aus. */
  toggleShowAllSimRoutes: () => void;
  /** Startet/stoppt die Stapler-Animation für einen Sim-Auftrag. */
  setAnimationActive: (id: string | null) => void;

  // Project Actions
  saveVorher: (snapshot: ProjektSnapshot, screenshot: string) => void;
  saveNachher: (snapshot: ProjektSnapshot, screenshot: string) => void;
  loadSnapshot: (type: 'vorher' | 'nachher') => void;

  // Bulk Actions
  resetState: () => void;
  loadState: (state: Partial<TopisState>) => void;

  // Path-Recompute (Lastenheft 3.1.4.2 — automatische Aktualisierung)
  recomputeAllPaths: () => void;
  scheduleRecomputeForObject: (objectId: number) => void;

  // ===== Lastenheft-Aufholplan 2026-05-31 — Bereichseinteilung (3.2.5) =====
  addBereichsEinteilung: (b: Omit<import('@/types/topis').BereichsEinteilung, 'id'>) => void;
  updateBereichsEinteilung: (id: number, updates: Partial<import('@/types/topis').BereichsEinteilung>) => void;
  deleteBereichsEinteilung: (id: number) => void;
  // ===== Lastenheft-Aufholplan 2026-05-31 — Format Übertragen (3.1.1.2) =====
  setFormatClipboard: (sourceId: number, properties: string[]) => void;
  applyFormatTo: (targetId: number) => void;
  clearFormatClipboard: () => void;
  // ===== Lastenheft-Aufholplan 2026-05-31 — Druck/Bildschirm-Modus (3.1.7) =====
  setAnsichtsModus: (modus: 'bildschirm' | 'druck') => void;

  // ===== Lastenheft Kapitel 4 — Verlader =====
  addVerlader: (v: Omit<import('@/types/topis').Verlader, 'id'>) => import('@/types/topis').Verlader;
  updateVerlader: (id: number, updates: Partial<import('@/types/topis').Verlader>) => void;
  deleteVerlader: (id: number) => void;
  selectVerlader: (v: import('@/types/topis').Verlader | null) => void;

  // ===== Lastenheft 3.2.1 — Prozess-/Mengen-Modell =====
  addProzesskategorie: (name: string, subprozesse?: string[]) => void;
  updateProzesskategorie: (id: number, updates: Partial<Omit<import('@/types/topis').Prozesskategorie, 'id'>>) => void;
  deleteProzesskategorie: (id: number) => void;
  addMengenEintrag: (entry: Omit<import('@/types/topis').MengenEintrag, 'id'>) => void;
  updateMengenEintrag: (id: number, updates: Partial<Omit<import('@/types/topis').MengenEintrag, 'id'>>) => void;
  deleteMengenEintrag: (id: number) => void;
  importMengenFromCsv: (csvText: string, modus: 'append' | 'replace') => import('./mengen-store-actions').CsvImportResult;

  // ===== Lastenheft 3.1.5 — Unterflurförderkette =====
  addKette: (kette: Omit<import('@/types/topis').KettenWegbereich, 'id'>) => import('@/types/topis').KettenWegbereich;
  updateKette: (id: number, updates: Partial<import('@/types/topis').KettenWegbereich>) => void;
  deleteKette: (id: number) => void;
  selectKette: (k: import('@/types/topis').KettenWegbereich | null) => void;
  addPunktToActiveKette: (punkt: { x: number; y: number }) => void;
}

const initialState: TopisState = {
  halls: [{ ...DEFAULT_HALL }],
  activeHallId: 1,
  hall: {
    width: DEFAULT_HALL.width,
    height: DEFAULT_HALL.height,
    shape: DEFAULT_HALL.shape,
    walls: []
  },
  objects: [],
  objectIdCounter: 1,
  selectedObject: null,
  paths: [],
  pathIdCounter: 1,
  selectedPath: null,
  currentPath: null,
  pathAreas: [],
  pathAreaIdCounter: 1,
  mittlereWegRuns: [],
  mittlererWegRunIdCounter: 1,
  gaenge: [],
  showGaenge: true,
  selectedGang: null,
  ffz: [...DEFAULT_FFZ],
  selectedPathArea: null,
  conveyors: [],
  conveyorIdCounter: 1,
  selectedConveyor: null,
  currentConveyor: null,
  cockpitRoute: null,
  simAuftraege: [],
  simAuftragPending: null,
  focusedTorId: null,
  showAllSimRoutes: false,
  animationActiveId: null,
  zoom: 1,
  pan: { x: 0, y: 0 },
  gridSize: 1,
  showGrid: true,
  snapToGrid: true,
  currentTool: 'select',
  nlGhost: null,
  nlBuilderOpen: false,
  _hydrated: false,
  filterType: 'all',
  projektVergleich: {
    vorher: null,
    nachher: null,
    vorherScreenshot: null,
    nachherScreenshot: null
  },
  // Lastenheft-Aufholplan 2026-05-31
  prozesskategorien: [],
  prozesskategorieIdCounter: 1,
  mengenEintraege: [],
  mengenEintragIdCounter: 1,
  kettenWegbereiche: [],
  kettenWegbereichIdCounter: 1,
  selectedKette: null,
  bereichsEinteilungen: [],
  bereichsEinteilungIdCounter: 1,
  aussengelaende: [],
  aussengelaendeIdCounter: 1,
  formatClipboard: null,
  ansichtsModus: 'bildschirm',
  // Lastenheft Kapitel 4 — Verlader
  verlader: [],
  verladerIdCounter: 1,
  selectedVerlader: null
};

export const useTopisStore = create<TopisStore>()(
  persist(
  (set, get) => ({
  ...initialState,

  // Undo/Redo state
  undoStack: [],
  redoStack: [],
  originalLayout: null,

  pushSnapshot: () => set((state) => {
    const snapshot = captureLayoutSnapshot(state);
    const newStack = [...state.undoStack, snapshot].slice(-MAX_UNDO_STACK);
    return { undoStack: newStack, redoStack: [] };
  }),

  undo: () => {
    const { undoStack } = get();
    if (undoStack.length === 0) return;

    const currentSnapshot = captureLayoutSnapshot(get());
    const previousSnapshot = undoStack[undoStack.length - 1];
    const restored = restoreLayoutSnapshot(previousSnapshot);

    set((state) => ({
      ...restored,
      undoStack: state.undoStack.slice(0, -1),
      redoStack: [...state.redoStack, currentSnapshot],
    }));
  },

  redo: () => {
    const { redoStack } = get();
    if (redoStack.length === 0) return;

    const currentSnapshot = captureLayoutSnapshot(get());
    const nextSnapshot = redoStack[redoStack.length - 1];
    const restored = restoreLayoutSnapshot(nextSnapshot);

    set((state) => ({
      ...restored,
      undoStack: [...state.undoStack, currentSnapshot],
      redoStack: state.redoStack.slice(0, -1),
    }));
  },

  canUndo: () => get().undoStack.length > 0,
  canRedo: () => get().redoStack.length > 0,

  saveOriginalLayout: () => set((state) => ({
    originalLayout: captureLayoutSnapshot(state),
  })),

  resetToOriginal: () => {
    const { originalLayout } = get();
    if (!originalLayout) return;
    const currentSnapshot = captureLayoutSnapshot(get());
    const restored = restoreLayoutSnapshot(originalLayout);
    set((state) => ({
      ...restored,
      undoStack: [...state.undoStack, currentSnapshot],
      redoStack: [],
    }));
  },

  // Hall Actions
  setHalls: (halls) => {
    get().pushSnapshot();
    set((state) => {
      const activeHall = halls.find((h) => h.id === state.activeHallId);
      // Lastenheft 3.1.1.1 — Außenwände aus der Hallen-Geometrie ableiten.
      const activeWalls = activeHall ? deriveWalls(activeHall) : [];
      // Lastenheft 3.1.2 — Tore folgen Wand-Geometrie automatisch
      const reanchored = activeWalls.length > 0 ? reanchorTore(state.objects, activeWalls) : state.objects;
      return { halls, objects: reanchored };
    });
  },
  setActiveHall: (id) => set({ activeHallId: id }),
  updateHall: (id, updates) => {
    get().pushSnapshot();
    set((state) => {
      const halls = state.halls.map(h => h.id === id ? { ...h, ...updates } : h);
      // Legacy state.hall mit aktiver Halle synchron halten (A2 28.05.):
      // Sonst zeigt state.hall.width/height den initialen Default statt der
      // geladenen Hallen-Größe — Drift zwischen Canvas-Anzeige und State.
      const legacyHall = id === state.activeHallId
        ? { ...state.hall, ...updates }
        : state.hall;
      // Lastenheft 3.1.2 — Wand-Änderungen ziehen Tore mit
      const activeHall = halls.find((h) => h.id === id);
      // Lastenheft 3.1.1.1 — Außenwände aus aktualisierter Geometrie ableiten.
      const activeWalls = id === state.activeHallId && activeHall
        ? deriveWalls(activeHall)
        : null;
      const reanchored = activeWalls && activeWalls.length > 0
        ? reanchorTore(state.objects, activeWalls)
        : state.objects;
      return { halls, hall: legacyHall, objects: reanchored };
    });
  },

  rotateHall90: () => {
    get().pushSnapshot();
    set((state) => {
      const hall = state.halls.find(h => h.id === state.activeHallId);
      if (!hall) return state;

      const oldWidth = hall.width;
      const oldHeight = hall.height;

      const rotatedObjects = state.objects.map(obj => ({
        ...obj,
        x: Math.round(obj.y),
        y: Math.round(oldWidth - obj.x - obj.width),
        width: obj.height,
        height: obj.width
      }));

      const rotatedHalls = state.halls.map(h =>
        h.id === state.activeHallId
          ? { ...h, width: oldHeight, height: oldWidth }
          : h
      );

      return { halls: rotatedHalls, objects: rotatedObjects };
    });
  },

  // Object Actions
  addObject: (obj) => {
    get().pushSnapshot();
    const id = get().objectIdCounter;
    let newObj = { ...obj, id } as TopisObject;
    // Lastenheft 3.1.2 — Tor wird automatisch an nächste Außenwand verankert.
    // Wenn der Aufrufer kein aussenwandRef gesetzt hat, suchen wir es per
    // findNearestWall. Wenn keine Wand in Reichweite ist, bleibt das Tor
    // unverankert (Migration alter Layouts / freie Halle ohne Wand-Geometrie).
    // Tore ragen nach innen (torBoxFromAnchor), Rampen liegen außen an der Wand
    // (rampeBoxFromAnchor, Lastenheft 3.1.2.2). Beide verankern an die nächste
    // Außenwand, wenn der Aufrufer kein aussenwandRef gesetzt hat.
    if ((newObj.type === 'tor' || newObj.type === 'rampe') && !newObj.aussenwandRef) {
      const activeHall = get().halls.find((h) => h.id === get().activeHallId);
      const walls = activeHall ? deriveWalls(activeHall) : [];
      if (walls.length > 0) {
        // Klickpunkt ist Mitte des Rechtecks
        const px = newObj.x + newObj.width / 2;
        const py = newObj.y + newObj.height / 2;
        const nearest = findNearestWall(px, py, walls, 30);
        if (nearest) {
          const anchor = { wallIndex: nearest.wallIndex, abstandS: nearest.abstandS, abstandE: nearest.abstandE };
          const box = newObj.type === 'rampe'
            ? rampeBoxFromAnchor(anchor, walls, newObj.width, newObj.height)
            : torBoxFromAnchor(anchor, walls, newObj.width, newObj.height);
          if (box) {
            newObj = {
              ...newObj,
              x: box.x,
              y: box.y,
              side: box.side ?? newObj.side,
              aussenwandRef: anchor,
            };
          }
        }
      }
    }
    set((state) => ({
      objects: [...state.objects, newObj],
      objectIdCounter: state.objectIdCounter + 1
    }));
    return newObj;
  },
  // Batch-Insert (z.B. Tor-Pinsel „Tor-Reihe"): EIN Undo-Schritt für die ganze
  // Reihe, EIN set(). Tore werden — wie in addObject — automatisch an die
  // nächste Außenwand verankert (deriveWalls + findNearestWall).
  addObjects: (objs) => {
    if (objs.length === 0) return [];
    get().pushSnapshot();
    const activeHall = get().halls.find((h) => h.id === get().activeHallId);
    const walls = activeHall ? deriveWalls(activeHall) : [];
    let counter = get().objectIdCounter;
    const created: TopisObject[] = [];
    for (const obj of objs) {
      let newObj = { ...obj, id: counter } as TopisObject;
      if ((newObj.type === 'tor' || newObj.type === 'rampe') && !newObj.aussenwandRef && walls.length > 0) {
        const px = newObj.x + newObj.width / 2;
        const py = newObj.y + newObj.height / 2;
        const nearest = findNearestWall(px, py, walls, 30);
        if (nearest) {
          const anchor = { wallIndex: nearest.wallIndex, abstandS: nearest.abstandS, abstandE: nearest.abstandE };
          const box = newObj.type === 'rampe'
            ? rampeBoxFromAnchor(anchor, walls, newObj.width, newObj.height)
            : torBoxFromAnchor(anchor, walls, newObj.width, newObj.height);
          if (box) {
            newObj = {
              ...newObj,
              x: box.x,
              y: box.y,
              side: box.side ?? newObj.side,
              aussenwandRef: anchor,
            };
          }
        }
      }
      created.push(newObj);
      counter += 1;
    }
    set((state) => ({
      objects: [...state.objects, ...created],
      objectIdCounter: counter,
    }));
    return created;
  },
  updateObject: (id, updates) => {
    get().pushSnapshot();
    set((state) => {
      const parent = state.objects.find(o => o.id === id);
      const updatedParent = parent ? { ...parent, ...updates } : null;
      // Parent-Bindung (Lastenheft 3.1.2 Überladebrücke): Kinder folgen
      // ihrem Parent bei x/y-Move. Width/Height-Updates lassen Kinder in Ruhe.
      const dx = (parent && updatedParent && updates.x !== undefined) ? (updatedParent.x - parent.x) : 0;
      const dy = (parent && updatedParent && updates.y !== undefined) ? (updatedParent.y - parent.y) : 0;
      const moved = dx !== 0 || dy !== 0;
      // Lastenheft 3.1.2 — Tor-Move soll Wand-Anker neu berechnen.
      // Wenn der User ein Tor verschiebt, snappen wir es zur nächsten Wand
      // und aktualisieren aussenwandRef. Außer der Aufrufer hat aussenwandRef
      // selbst gesetzt (z.B. aus PropertiesPanel S/E-Eingabe).
      const activeHall = state.halls.find((h) => h.id === state.activeHallId);
      const walls = activeHall ? deriveWalls(activeHall) : [];
      // Das tatsächlich gemergte (ggf. an Wand gesnappte) Objekt festhalten,
      // damit selectedObject NICHT nur ...updates bekommt — sonst zeigt das
      // PropertiesPanel die auto-gesetzte aussenwandRef nie an und die
      // „nicht verankert"-Warnung bleibt stehen (Niko-Bug 02.06.).
      let mergedSelected: TopisObject | null = null;
      const newObjects = state.objects.map(o => {
        if (o.id === id) {
          let merged = { ...o, ...updates };
          if (
            merged.type === 'tor' &&
            walls.length > 0 &&
            (updates.x !== undefined || updates.y !== undefined) &&
            updates.aussenwandRef === undefined
          ) {
            const px = merged.x + merged.width / 2;
            const py = merged.y + merged.height / 2;
            const nearest = findNearestWall(px, py, walls, 30);
            if (nearest) {
              const box = torBoxFromAnchor(
                { wallIndex: nearest.wallIndex, abstandS: nearest.abstandS, abstandE: nearest.abstandE },
                walls,
                merged.width,
                merged.height,
              );
              if (box) {
                merged = {
                  ...merged,
                  x: box.x,
                  y: box.y,
                  side: box.side ?? merged.side,
                  aussenwandRef: {
                    wallIndex: nearest.wallIndex,
                    abstandS: nearest.abstandS,
                    abstandE: nearest.abstandE,
                  },
                };
              }
            }
          } else if (
            merged.type === 'tor' &&
            walls.length > 0 &&
            updates.aussenwandRef !== undefined &&
            merged.aussenwandRef &&
            updates.x === undefined &&
            updates.y === undefined
          ) {
            // Lastenheft 3.1.2 — Abstand S/E im Panel direkt geändert: Tor muss
            // auf der Wand entlangwandern (Niko Schritt 5). x/y aus dem neuen
            // Anker neu berechnen, sonst ändert sich nur die Zahl, nicht das Tor.
            const box = torBoxFromAnchor(merged.aussenwandRef, walls, merged.width, merged.height);
            if (box) {
              merged = { ...merged, x: box.x, y: box.y, side: box.side ?? merged.side };
            }
          }
          mergedSelected = merged;
          return merged;
        }
        if (moved && o.parentObjectId === id) {
          return { ...o, x: o.x + dx, y: o.y + dy };
        }
        return o;
      });
      return {
        objects: newObjects,
        selectedObject: state.selectedObject?.id === id
          ? (mergedSelected ?? { ...state.selectedObject, ...updates })
          : state.selectedObject,
      };
    });
    if (updates.x !== undefined || updates.y !== undefined || updates.width !== undefined || updates.height !== undefined || updates.aussenwandRef !== undefined) {
      get().scheduleRecomputeForObject(id);
    }
  },
  deleteObject: (id) => {
    get().pushSnapshot();
    set((state) => {
      // Parent-Bindung (3.1.2): alle Kinder dieses Objekts mitlöschen
      const childIds = new Set<number>();
      const collectDescendants = (parentId: number) => {
        for (const o of state.objects) {
          if (o.parentObjectId === parentId && !childIds.has(o.id)) {
            childIds.add(o.id);
            collectDescendants(o.id);
          }
        }
      };
      collectDescendants(id);
      const idsToDelete = new Set([id, ...childIds]);
      return {
        objects: state.objects.filter(o => !idsToDelete.has(o.id)),
        selectedObject: state.selectedObject && idsToDelete.has(state.selectedObject.id) ? null : state.selectedObject,
        paths: state.paths.map(p => {
          const verwaist = (p.startObjectId != null && idsToDelete.has(p.startObjectId)) || (p.endObjectId != null && idsToDelete.has(p.endObjectId));
          if (!verwaist) return p;
          return { ...p, name: p.name.startsWith('⚠ ') ? p.name : `⚠ ${p.name}` };
        }),
        simAuftraege: state.simAuftraege.filter(a => !idsToDelete.has(a.vonObjectId) && !idsToDelete.has(a.nachObjectId)),
      };
    });
  },
  selectObject: (obj) => set({ selectedObject: obj, selectedPath: null, selectedGang: null, selectedPathArea: null, selectedConveyor: null, selectedKette: null }),

  // Path Actions
  addPath: (path) => {
    get().pushSnapshot();
    set((state) => ({
      paths: [...state.paths, { ...path, id: state.pathIdCounter }],
      pathIdCounter: state.pathIdCounter + 1
    }));
  },
  addPaths: (paths) => {
    if (paths.length === 0) return;
    get().pushSnapshot();
    set((state) => {
      let counter = state.pathIdCounter;
      const newPaths = paths.map(p => ({ ...p, id: counter++ }));
      return {
        paths: [...state.paths, ...newPaths],
        pathIdCounter: counter
      };
    });
  },
  updatePath: (id, updates) => set((state) => {
    const updatedPaths = state.paths.map(p => p.id === id ? { ...p, ...updates } : p);
    const updatedPath = updatedPaths.find(p => p.id === id) || null;
    return {
      paths: updatedPaths,
      selectedPath: state.selectedPath?.id === id ? updatedPath : state.selectedPath
    };
  }),
  deletePath: (id) => {
    get().pushSnapshot();
    set((state) => ({
      paths: state.paths.filter(p => p.id !== id),
      selectedPath: state.selectedPath?.id === id ? null : state.selectedPath
    }));
  },
  deleteAutoGeneratedPaths: () => {
    const hasAuto = get().paths.some(p => p.autoGenerated);
    if (!hasAuto) return;
    get().pushSnapshot();
    set((state) => ({
      paths: state.paths.filter(p => !p.autoGenerated),
      selectedPath: state.selectedPath?.autoGenerated ? null : state.selectedPath
    }));
  },
  selectPath: (path) => set({ selectedPath: path, selectedObject: null, selectedGang: null, selectedPathArea: null, selectedConveyor: null, selectedKette: null }),

  // PathArea Actions
  addPathArea: (area) => {
    get().pushSnapshot();
    const id = get().pathAreaIdCounter;
    const newArea = { ...area, id } as PathArea;
    const autoGangs = gaengeFuerPathArea(newArea);
    set((state) => {
      let gangIdNext = Math.max(0, ...state.gaenge.map(g => g.id)) + 1;
      const neueGaenge = autoGangs.map(g => ({ ...g, id: gangIdNext++ } as Gang));
      // Insel-Verbinder neu generieren: alte Connectoren (Namens-Präfix
      // „Auto: Verbinder") wegwerfen und auf Basis aller Auto-Gänge neu
      // rechnen — damit eine neu hinzugefügte pathArea ans Netz andockt.
      const ohneVerbinder = [...state.gaenge.filter(g => !g.name.startsWith('Auto: Verbinder')), ...neueGaenge];
      const connectors = generateConnectors(ohneVerbinder);
      const connectorGangs = connectors.map(g => ({ ...g, id: gangIdNext++ } as Gang));
      return {
        pathAreas: [...state.pathAreas, newArea],
        pathAreaIdCounter: state.pathAreaIdCounter + 1,
        gaenge: [...ohneVerbinder, ...connectorGangs],
      };
    });
    get().scheduleRecomputeForObject(-1);
    return newArea;
  },
  updatePathArea: (id, updates) => {
    set((state) => {
      const updatedAreas = state.pathAreas.map(a => a.id === id ? { ...a, ...updates } : a);
      const updatedPA = updatedAreas.find(a => a.id === id);
      // Auto-Gänge dieser pathArea + alle Verbinder entfernen, neu erzeugen
      const ohneAlteAutoGaenge = state.gaenge.filter(
        g => g.autoFromPathAreaId !== id && !g.name.startsWith('Auto: Verbinder')
      );
      let gangIdNext = Math.max(0, ...state.gaenge.map(g => g.id)) + 1;
      const neueAutoGaenge = updatedPA
        ? gaengeFuerPathArea(updatedPA).map(g => ({ ...g, id: gangIdNext++ } as Gang))
        : [];
      const basis = [...ohneAlteAutoGaenge, ...neueAutoGaenge];
      const connectors = generateConnectors(basis);
      const connectorGangs = connectors.map(g => ({ ...g, id: gangIdNext++ } as Gang));
      return {
        pathAreas: updatedAreas,
        gaenge: [...basis, ...connectorGangs],
        selectedPathArea: state.selectedPathArea?.id === id && updatedPA ? updatedPA : state.selectedPathArea,
      };
    });
    get().scheduleRecomputeForObject(-1);
  },
  deletePathArea: (id) => {
    get().pushSnapshot();
    set((state) => {
      const ohneArea = state.pathAreas.filter(a => a.id !== id);
      const ohneAutoGaenge = state.gaenge.filter(
        g => g.autoFromPathAreaId !== id && !g.name.startsWith('Auto: Verbinder')
      );
      let gangIdNext = Math.max(0, ...state.gaenge.map(g => g.id)) + 1;
      const connectors = generateConnectors(ohneAutoGaenge);
      const connectorGangs = connectors.map(g => ({ ...g, id: gangIdNext++ } as Gang));
      return {
        pathAreas: ohneArea,
        gaenge: [...ohneAutoGaenge, ...connectorGangs],
        selectedPathArea: state.selectedPathArea?.id === id ? null : state.selectedPathArea,
      };
    });
    get().scheduleRecomputeForObject(-1);
  },
  selectPathArea: (area) => set({ selectedPathArea: area, selectedObject: null, selectedPath: null, selectedConveyor: null, selectedGang: null, selectedKette: null }),

  // Mittlerer-Weg-Run Actions (Lastenheft 3.2.4)
  saveMittlererWegRun: (run) => {
    get().pushSnapshot();
    set((state) => ({
      mittlereWegRuns: [...state.mittlereWegRuns, { ...run, id: state.mittlererWegRunIdCounter }],
      mittlererWegRunIdCounter: state.mittlererWegRunIdCounter + 1,
    }));
  },
  deleteMittlererWegRun: (id) => {
    get().pushSnapshot();
    set((state) => ({ mittlereWegRuns: state.mittlereWegRuns.filter(r => r.id !== id) }));
  },

  // Gang Actions
  setGaenge: (gaenge) => { get().pushSnapshot(); set({ gaenge }); get().scheduleRecomputeForObject(-1); },
  addGang: (gang) => {
    get().pushSnapshot();
    set((state) => ({ gaenge: [...state.gaenge, gang] }));
    get().scheduleRecomputeForObject(-1);
  },
  updateGang: (id, updates) => {
    set((state) => {
      const updatedGaenge = state.gaenge.map(g => g.id === id ? { ...g, ...updates } : g);
      return {
        gaenge: updatedGaenge,
        selectedGang: state.selectedGang?.id === id
          ? { ...state.selectedGang, ...updates }
          : state.selectedGang
      };
    });
    get().scheduleRecomputeForObject(-1);
  },
  deleteGang: (id) => {
    get().pushSnapshot();
    set((state) => ({
      gaenge: state.gaenge.filter(g => g.id !== id),
      selectedGang: state.selectedGang?.id === id ? null : state.selectedGang
    }));
    get().scheduleRecomputeForObject(-1);
  },
  selectGang: (gang) => set({ selectedGang: gang, selectedObject: null, selectedPath: null, selectedConveyor: null, selectedPathArea: null, selectedKette: null }),
  toggleShowGaenge: () => set((state) => ({ showGaenge: !state.showGaenge })),

  // FFZ Actions
  setFFZ: (ffz) => set({ ffz }),

  // Conveyor Actions
  addConveyor: (conveyor) => {
    get().pushSnapshot();
    const id = get().conveyorIdCounter;
    const newConveyor = { ...conveyor, id } as Conveyor;
    set((state) => ({
      conveyors: [...state.conveyors, newConveyor],
      conveyorIdCounter: state.conveyorIdCounter + 1
    }));
    return newConveyor;
  },
  updateConveyor: (id, updates) => set((state) => {
    const updatedConveyors = state.conveyors.map(c => c.id === id ? { ...c, ...updates } : c);
    return {
      conveyors: updatedConveyors,
      selectedConveyor: state.selectedConveyor?.id === id
        ? { ...state.selectedConveyor, ...updates }
        : state.selectedConveyor
    };
  }),
  deleteConveyor: (id) => {
    get().pushSnapshot();
    set((state) => ({
      conveyors: state.conveyors.filter(c => c.id !== id),
      selectedConveyor: state.selectedConveyor?.id === id ? null : state.selectedConveyor
    }));
  },
  selectConveyor: (conveyor) => set({ selectedConveyor: conveyor, selectedObject: null, selectedPath: null, selectedGang: null, selectedPathArea: null, selectedKette: null }),

  // View Actions
  setZoom: (zoom) => set({ zoom: Math.max(0.1, Math.min(5, zoom)) }),
  setPan: (pan) => set({ pan }),
  setTool: (tool) => set({ currentTool: tool }),
  setNlGhost: (g) => set({ nlGhost: g }),
  setNlBuilderOpen: (open) => set({ nlBuilderOpen: open }),
  toggleGrid: () => set((state) => ({ showGrid: !state.showGrid })),
  toggleSnap: () => set((state) => ({ snapToGrid: !state.snapToGrid })),
  setCockpitRoute: (route) => set({ cockpitRoute: route }),

  startSimAuftrag: (vonObjectId) => set({ simAuftragPending: { vonObjectId } }),
  cancelSimAuftrag: () => set({ simAuftragPending: null }),
  finishSimAuftrag: (nachObjectId, colli, notiz) => set((state) => {
    const pending = state.simAuftragPending;
    if (!pending) return state;
    const auftrag = {
      id: `sim-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      vonObjectId: pending.vonObjectId,
      nachObjectId,
      colli,
      notiz,
    };
    return {
      simAuftraege: [...state.simAuftraege, auftrag],
      simAuftragPending: null,
    };
  }),
  updateSimAuftrag: (id, patch) => set((state) => ({
    simAuftraege: state.simAuftraege.map((a) => (a.id === id ? { ...a, ...patch } : a)),
  })),
  removeSimAuftrag: (id) => set((state) => ({
    simAuftraege: state.simAuftraege.filter((a) => a.id !== id),
  })),
  clearSimAuftraege: () => set({ simAuftraege: [], simAuftragPending: null }),
  forkSimAuftragAsSim: (parentId, neuerNachObjectId, neueColli) => set((state) => {
    const parent = state.simAuftraege.find((a) => a.id === parentId);
    if (!parent) return state;
    // Existierende SIM zu diesem Parent entfernen
    const ohneAlteSim = state.simAuftraege.filter((a) => a.parentId !== parentId);
    const sim = {
      id: `sim-fork-${parentId}-${Date.now().toString(36)}`,
      vonObjectId: parent.vonObjectId,
      nachObjectId: neuerNachObjectId,
      colli: neueColli ?? parent.colli,
      notiz: `Simulation von ${parent.notiz ?? parent.id}`,
      parentId,
    };
    return { simAuftraege: [...ohneAlteSim, sim] };
  }),
  removeSimVarianteFor: (parentId) => set((state) => ({
    simAuftraege: state.simAuftraege.filter((a) => a.parentId !== parentId),
  })),
  setFocusedTor: (id) => set({ focusedTorId: id }),
  toggleShowAllSimRoutes: () => set((state) => ({ showAllSimRoutes: !state.showAllSimRoutes })),
  setAnimationActive: (id) => set({ animationActiveId: id }),
  seedBeispielAuftraege: () => {
    // Dynamic import nicht möglich in der Set-Funktion; wir lassen die
    // Beispielliste hier inline (klein, Demo-Zweck).
    const state = get();
    const tore = state.objects.filter((o) => o.type === 'tor');
    if (tore.length < 2) return 0;
    const samples: Array<{ vonNr: number; nachNr: number; colli: number; notiz: string }> = [
      { vonNr: 5,   nachNr: 88,  colli: 1200, notiz: 'Süd → Nord, lang' },
      { vonNr: 12,  nachNr: 102, colli: 800,  notiz: 'Süd → Nord-Ost' },
      { vonNr: 18,  nachNr: 75,  colli: 1500, notiz: 'Süd → Nord, kurz' },
      { vonNr: 25,  nachNr: 67,  colli: 600,  notiz: 'Süd-Mitte → Nord-West' },
      { vonNr: 47,  nachNr: 95,  colli: 2000, notiz: 'Süd-Ost → Nord, lang' },
      { vonNr: 53,  nachNr: 78,  colli: 450,  notiz: 'Kopframpe → Nord' },
      { vonNr: 8,   nachNr: 110, colli: 1100, notiz: 'Süd → Nord-Ost, lang' },
      { vonNr: 35,  nachNr: 70,  colli: 900,  notiz: 'Süd-Mitte → Nord' },
      { vonNr: 22,  nachNr: 82,  colli: 700,  notiz: 'Süd → Nord, mittel' },
      { vonNr: 41,  nachNr: 105, colli: 1300, notiz: 'Süd-Ost → Nord-Ost' },
    ];
    const findTor = (nr: number) => {
      const exact = tore.find((t) => t.torNummer === nr);
      if (exact) return exact;
      let best = tore[0];
      let bestDiff = Infinity;
      for (const t of tore) {
        if (t.torNummer == null) continue;
        const diff = Math.abs(t.torNummer - nr);
        if (diff < bestDiff) { best = t; bestDiff = diff; }
      }
      return best;
    };
    const neu = samples
      .map((s) => {
        const von = findTor(s.vonNr);
        const nach = findTor(s.nachNr);
        if (!von || !nach || von.id === nach.id) return null;
        return {
          id: `sim-seed-${s.vonNr}-${s.nachNr}-${Date.now().toString(36)}`,
          vonObjectId: von.id,
          nachObjectId: nach.id,
          colli: s.colli,
          notiz: s.notiz,
        };
      })
      .filter((x): x is NonNullable<typeof x> => x !== null);
    // Ohne Gangnetz finden die Aufträge keine Wege ("Pfad nicht gefunden").
    // Wenn noch keine Gänge existieren, ein Basis-Netz aus den Toren erzeugen.
    let gaengePatch: Partial<TopisState> = {};
    if (state.gaenge.length === 0) {
      const hall = state.halls.find((h) => h.id === state.activeHallId) ?? state.halls[0];
      if (hall) {
        const net = generateBasicGangNet(tore, hall.width, hall.height, 1);
        if (net.length > 0) gaengePatch = { gaenge: net };
      }
    }
    set({
      simAuftraege: [...state.simAuftraege, ...neu],
      simAuftragPending: null,
      ...gaengePatch,
    });
    return neu.length;
  },

  // Project Actions
  saveVorher: (snapshot, screenshot) => set((state) => ({
    projektVergleich: {
      ...state.projektVergleich,
      vorher: snapshot,
      vorherScreenshot: screenshot
    }
  })),
  saveNachher: (snapshot, screenshot) => set((state) => ({
    projektVergleich: {
      ...state.projektVergleich,
      nachher: snapshot,
      nachherScreenshot: screenshot
    }
  })),
  loadSnapshot: (type) => {
    const snapshot = get().projektVergleich[type];
    if (!snapshot) return;

    set({
      halls: structuredClone(snapshot.halls),
      objects: structuredClone(snapshot.objects),
      paths: structuredClone(snapshot.paths),
      pathAreas: structuredClone(snapshot.pathAreas),
      gaenge: structuredClone(snapshot.gaenge),
      ffz: structuredClone(snapshot.ffz),
      conveyors: structuredClone(snapshot.conveyors),
    });
  },

  // Bulk Actions
  resetState: () => set({ ...initialState, undoStack: [], redoStack: [], originalLayout: null, _hydrated: true }),
  loadState: (newState) => set((state) => ({ ...state, ...newState })),

  /**
   * Berechnet alle Paths mit gesetztem startObjectId/endObjectId neu — basierend
   * auf den aktuellen Object-Positionen und dem Gang-Netz. Manuell gezeichnete
   * Wege ohne Verknüpfung bleiben unverändert (Lastenheft 3.1.4.2: nur
   * verknüpfte Wege werden aktualisiert).
   */
  recomputeAllPaths: () => {
    const state = get();
    const graph = buildGangGraph(state.gaenge);
    const walls = state.objects.filter((o) => {
      if (o.istUndurchlaessig === false) return false;
      if (o.istUndurchlaessig === true) return true;
      if (o.type === 'tuer') return true; // Tür-Region wird in lineCrossesAnyWall als Durchlass behandelt
      return o.type === 'wand' || o.type === 'bereich' || o.type === 'regal' || o.type === 'hindernis';
    });
    const byId = new Map(state.objects.map((o) => [o.id, o]));
    let changed = false;
    const newPaths = state.paths.map((p) => {
      // Variante A: Pfad mit Stützpunkten (3+ User-Klicks) → A* zwischen jedem
      // Paar, Stützpunkte bleiben anker-treu zur User-Intention.
      if (p.stuetzpunkte && p.stuetzpunkte.length >= 2) {
        const stitched: { x: number; y: number; objectId: number | null }[] = [];
        let totalDist = 0;
        let totalTime = 0;
        let anyChanged = false;
        for (let i = 0; i + 1 < p.stuetzpunkte.length; i++) {
          const a = p.stuetzpunkte[i];
          const b = p.stuetzpunkte[i + 1];
          const r = findPath(a.x, a.y, b.x, b.y, graph, undefined, walls, state.pathAreas);
          if (r && r.path.length >= 2) {
            anyChanged = true;
            const pts = stitched.length === 0 ? r.path : r.path.slice(1);
            pts.forEach((pt) => stitched.push({ x: pt.x, y: pt.y, objectId: null }));
            totalDist += r.distance;
            totalTime += r.time;
          } else {
            if (stitched.length === 0) stitched.push({ ...a });
            stitched.push({ ...b });
          }
        }
        if (anyChanged) {
          changed = true;
          return { ...p, waypoints: stitched, distance: totalDist, time: totalTime };
        }
        return p;
      }
      // Variante B: Pfad nur mit Anker-Objekten (2-Anker-Auto-Route)
      if (p.startObjectId == null || p.endObjectId == null) return p;
      const from = byId.get(p.startObjectId);
      const to = byId.get(p.endObjectId);
      if (!from || !to) return p; // verwaister Path — bleibt als „Geister"-Geometrie, später Cleanup
      const r = findPathBetweenObjects(from, to, graph, undefined, walls, state.pathAreas);
      if (!r) return p;
      changed = true;
      return {
        ...p,
        waypoints: r.path.map((pt) => ({ x: pt.x, y: pt.y, objectId: null })),
        distance: r.distance,
        time: r.time,
      };
    });
    if (changed) set({ paths: newPaths });
  },

  scheduleRecomputeForObject: (_objectId: number) => {
    // Debounce: erst nach 80 ms Maus-Ruhe recomputen (Drag-Frame-Stürme abfangen).
    // _objectId aktuell nicht ausgewertet — alle Paths werden recomputed; das
    // ist ok bei einer überschaubaren Path-Anzahl, könnte später indexiert werden.
    if (_recomputeTimer != null) clearTimeout(_recomputeTimer);
    _recomputeTimer = setTimeout(() => {
      _recomputeTimer = null;
      get().recomputeAllPaths();
    }, 80) as unknown as number;
  },

  // ===== Lastenheft-Aufholplan 2026-05-31 — Bereichseinteilung (3.2.5) =====
  addBereichsEinteilung: (b) => {
    get().pushSnapshot();
    set((state) => ({
      bereichsEinteilungen: [...state.bereichsEinteilungen, { ...b, id: state.bereichsEinteilungIdCounter }],
      bereichsEinteilungIdCounter: state.bereichsEinteilungIdCounter + 1,
    }));
  },
  updateBereichsEinteilung: (id, updates) => {
    get().pushSnapshot();
    set((state) => ({
      bereichsEinteilungen: state.bereichsEinteilungen.map((b) => b.id === id ? { ...b, ...updates } : b),
    }));
  },
  deleteBereichsEinteilung: (id) => {
    get().pushSnapshot();
    set((state) => ({
      bereichsEinteilungen: state.bereichsEinteilungen.filter((b) => b.id !== id),
    }));
  },

  // ===== Lastenheft-Aufholplan 2026-05-31 — Format Übertragen (3.1.1.2) =====
  setFormatClipboard: (sourceObjectId, propertyNames) => {
    set({ formatClipboard: { sourceObjectId, propertyNames } });
  },
  applyFormatTo: (targetId) => {
    const clip = get().formatClipboard;
    if (!clip) return;
    const source = get().objects.find((o) => o.id === clip.sourceObjectId);
    if (!source) return;
    const patch: Partial<TopisObject> = {};
    for (const prop of clip.propertyNames) {
      const value = (source as unknown as Record<string, unknown>)[prop];
      if (value !== undefined) {
        (patch as Record<string, unknown>)[prop] = value;
      }
    }
    get().updateObject(targetId, patch);
  },
  clearFormatClipboard: () => set({ formatClipboard: null }),

  // ===== Lastenheft-Aufholplan 2026-05-31 — Druck/Bildschirm-Modus (3.1.7) =====
  setAnsichtsModus: (modus) => set({ ansichtsModus: modus }),

  // ===== Lastenheft Kapitel 4 — Verlader =====
  addVerlader: (v) => {
    get().pushSnapshot();
    const neu: Verlader = { ...v, id: get().verladerIdCounter };
    set((state) => ({
      verlader: [...state.verlader, neu],
      verladerIdCounter: state.verladerIdCounter + 1,
    }));
    return neu;
  },
  updateVerlader: (id, updates) => {
    get().pushSnapshot();
    set((state) => ({
      verlader: state.verlader.map((vl) => (vl.id === id ? { ...vl, ...updates } : vl)),
      selectedVerlader:
        state.selectedVerlader && state.selectedVerlader.id === id
          ? { ...state.selectedVerlader, ...updates }
          : state.selectedVerlader,
    }));
  },
  deleteVerlader: (id) => {
    get().pushSnapshot();
    set((state) => ({
      verlader: state.verlader.filter((vl) => vl.id !== id),
      selectedVerlader:
        state.selectedVerlader && state.selectedVerlader.id === id ? null : state.selectedVerlader,
    }));
  },
  selectVerlader: (vl) => set({ selectedVerlader: vl }),

  // ===== Lastenheft 3.2.1 — Prozess-/Mengen-Modell =====
  addProzesskategorie: (name, subprozesse) => {
    get().pushSnapshot();
    set((state) => mengenActions.addProzesskategoriePatch(state, name, subprozesse));
  },
  updateProzesskategorie: (id, updates) => {
    get().pushSnapshot();
    set((state) => mengenActions.updateProzesskategoriePatch(state, id, updates));
  },
  deleteProzesskategorie: (id) => {
    get().pushSnapshot();
    set((state) => mengenActions.deleteProzesskategoriePatch(state, id));
  },
  addMengenEintrag: (entry) => {
    get().pushSnapshot();
    set((state) => mengenActions.addMengenEintragPatch(state, entry));
  },
  updateMengenEintrag: (id, updates) => {
    get().pushSnapshot();
    set((state) => mengenActions.updateMengenEintragPatch(state, id, updates));
  },
  deleteMengenEintrag: (id) => {
    get().pushSnapshot();
    set((state) => mengenActions.deleteMengenEintragPatch(state, id));
  },
  importMengenFromCsv: (csvText, modus) => {
    get().pushSnapshot();
    const result = mengenActions.importMengenFromCsv(get(), csvText, modus);
    set(result.patch);
    return result;
  },

  // ===== Lastenheft 3.1.5 — Unterflurförderkette =====
  addKette: (kette) => {
    get().pushSnapshot();
    const id = get().kettenWegbereichIdCounter;
    const neu: import('@/types/topis').KettenWegbereich = { ...kette, id };
    set((state) => ({
      kettenWegbereiche: [...state.kettenWegbereiche, neu],
      kettenWegbereichIdCounter: state.kettenWegbereichIdCounter + 1,
      selectedKette: neu,
      selectedObject: null,
      selectedPath: null,
      selectedGang: null,
      selectedPathArea: null,
      selectedConveyor: null,
    }));
    return neu;
  },
  updateKette: (id, updates) => {
    set((state) => {
      const ketten = state.kettenWegbereiche.map((k) =>
        k.id === id ? { ...k, ...updates } : k,
      );
      const aktualisiert = ketten.find((k) => k.id === id) ?? null;
      return {
        kettenWegbereiche: ketten,
        selectedKette: state.selectedKette?.id === id ? aktualisiert : state.selectedKette,
      };
    });
  },
  deleteKette: (id) => {
    get().pushSnapshot();
    set((state) => ({
      kettenWegbereiche: state.kettenWegbereiche.filter((k) => k.id !== id),
      selectedKette: state.selectedKette?.id === id ? null : state.selectedKette,
    }));
  },
  selectKette: (k) =>
    set({
      selectedKette: k,
      selectedObject: null,
      selectedPath: null,
      selectedGang: null,
      selectedPathArea: null,
      selectedConveyor: null,
    }),
  addPunktToActiveKette: (punkt) => {
    const aktive = get().selectedKette;
    if (!aktive) return;
    set((state) => {
      const ketten = state.kettenWegbereiche.map((k) =>
        k.id === aktive.id ? { ...k, punkte: [...k.punkte, { x: punkt.x, y: punkt.y }] } : k,
      );
      const updated = ketten.find((k) => k.id === aktive.id) ?? null;
      return { kettenWegbereiche: ketten, selectedKette: updated };
    });
  },
}),
  {
    name: 'topis-layout',
    storage: createJSONStorage(() => createDebouncedLocalStorage()),
    // ===== SCHEMA-VERSION & MIGRATIONEN =====
    // Bei JEDER Änderung der gespeicherten Datenform (Feld umbenennen/entfernen,
    // Objektstruktur ändern, neues Pflichtfeld): version erhöhen UND unten einen
    // Migrationsschritt von der Vorgängerversion ergänzen. Gilt für localStorage
    // UND Cloud-Layouts (die speichern dieselbe {state, version}-Struktur).
    // Vor riskanten Änderungen: scripts/backup-cloud-layouts.sh laufen lassen.
    version: 1,
    migrate: (persisted: unknown, fromVersion: number) => {
      let s = persisted as Record<string, unknown>;
      // v0 → v1: Baseline. Datenform unverändert; die Tor-Verankerung wird
      // idempotent in onRehydrateStorage nachgezogen (keine Strukturänderung).
      if (fromVersion < 1) {
        // (keine Transformation nötig)
      }
      // Künftige Schritte hier anhängen, z.B.:
      // if (fromVersion < 2) { s = migrateV1toV2(s); }
      return s;
    },
    // Migration (Niko-Bug 02.06.): Vor dem Fix gespeicherte Tore haben kein
    // aussenwandRef → die „nicht verankert"-Warnung bliebe für sie dauerhaft
    // stehen, auch wenn sie längst auf einer Wand sitzen. Beim Rehydrieren
    // jedes unverankerte Tor an die nächste abgeleitete Außenwand binden.
    onRehydrateStorage: () => (state) => {
      if (!state) return;
      state._hydrated = true; // Rehydration abgeschlossen → Empty-State-Flash vermeiden
      const activeHall = state.halls?.find((h) => h.id === state.activeHallId);
      const walls = activeHall ? deriveWalls(activeHall) : [];
      if (walls.length === 0) return;
      state.objects = state.objects.map((o) => {
        if (o.type !== 'tor' || o.aussenwandRef) return o;
        const nearest = findNearestWall(o.x + o.width / 2, o.y + o.height / 2, walls, 30);
        if (!nearest) return o;
        const ref = { wallIndex: nearest.wallIndex, abstandS: nearest.abstandS, abstandE: nearest.abstandE };
        const box = torBoxFromAnchor(ref, walls, o.width, o.height);
        return box
          ? { ...o, x: box.x, y: box.y, side: box.side ?? o.side, aussenwandRef: ref }
          : { ...o, aussenwandRef: ref };
      });
    },
    partialize: (state) => ({
      halls: state.halls,
      activeHallId: state.activeHallId,
      hall: state.hall,
      objects: state.objects,
      objectIdCounter: state.objectIdCounter,
      paths: state.paths,
      pathIdCounter: state.pathIdCounter,
      pathAreas: state.pathAreas,
      pathAreaIdCounter: state.pathAreaIdCounter,
      mittlereWegRuns: state.mittlereWegRuns,
      mittlererWegRunIdCounter: state.mittlererWegRunIdCounter,
      gaenge: state.gaenge,
      ffz: state.ffz,
      conveyors: state.conveyors,
      conveyorIdCounter: state.conveyorIdCounter,
      simAuftraege: state.simAuftraege,
      focusedTorId: state.focusedTorId,
      animationActiveId: state.animationActiveId,
      // Lastenheft-Aufholplan 2026-05-31
      bereichsEinteilungen: state.bereichsEinteilungen,
      bereichsEinteilungIdCounter: state.bereichsEinteilungIdCounter,
      prozesskategorien: state.prozesskategorien,
      prozesskategorieIdCounter: state.prozesskategorieIdCounter,
      mengenEintraege: state.mengenEintraege,
      mengenEintragIdCounter: state.mengenEintragIdCounter,
      kettenWegbereiche: state.kettenWegbereiche,
      kettenWegbereichIdCounter: state.kettenWegbereichIdCounter,
      aussengelaende: state.aussengelaende,
      aussengelaendeIdCounter: state.aussengelaendeIdCounter,
      ansichtsModus: state.ansichtsModus,
      // Lastenheft Kapitel 4 — Verlader
      verlader: state.verlader,
      verladerIdCounter: state.verladerIdCounter,
    }),
  }
));

// Selector hooks for performance
export const useObjects = () => useTopisStore((state) => state.objects);
// O(1)-Lookup-Index — wird bei jeder objects-Änderung neu erzeugt, ist aber
// pro Render nur einmal in jedem Consumer nötig (statt 100x objects.find).
const _objectIndexCache = { ref: null as TopisObject[] | null, map: new Map<number, TopisObject>() };
export const useObjectIndex = (): Map<number, TopisObject> => useTopisStore((state) => {
  if (_objectIndexCache.ref !== state.objects) {
    _objectIndexCache.ref = state.objects;
    _objectIndexCache.map = new Map(state.objects.map(o => [o.id, o]));
  }
  return _objectIndexCache.map;
});
export const useSelectedObject = () => useTopisStore((state) => state.selectedObject);
export const useHalls = () => useTopisStore((state) => state.halls);
export const useActiveHall = () => useTopisStore((state) =>
  state.halls.find(h => h.id === state.activeHallId) || state.halls[0]
);

// Rehydration-Flag zuverlässig setzen (Draft-Mutation in onRehydrateStorage greift in
// zustand v5 NICHT auf den Live-State) → verhindert den "0 Objekte"-Flash beim Reload.
if (typeof window !== 'undefined') {
  const markHydrated = () => useTopisStore.setState({ _hydrated: true });
  useTopisStore.persist.onFinishHydration(markHydrated);
  if (useTopisStore.persist.hasHydrated()) markHydrated();
}

// E2E-Hook: Store im Browser zugänglich machen, damit Tests den Live-Zustand
// (inkl. nicht-persistiertem selectedObject) lesen können. Read-only Referenz.
if (typeof window !== 'undefined') {
  (window as unknown as { __topisStore?: typeof useTopisStore }).__topisStore = useTopisStore;
}

export const useTool = () => useTopisStore((state) => state.currentTool);
export const useZoom = () => useTopisStore((state) => state.zoom);
export const usePan = () => useTopisStore((state) => state.pan);
export const useSelectedGang = () => useTopisStore((state) => state.selectedGang);
export const useSelectedPathArea = () => useTopisStore((state) => state.selectedPathArea);
export const useSelectedConveyor = () => useTopisStore((state) => state.selectedConveyor);
export const useKettenWegbereiche = () => useTopisStore((state) => state.kettenWegbereiche);
export const useSelectedKette = () => useTopisStore((state) => state.selectedKette);
