'use client';

import { useState, useMemo } from 'react';
import { useTopisStore } from '@/lib/store';
import { useProzessmodellStore } from '@/lib/prozessmodell-store';
import { useBetriebsdatenStore } from '@/lib/betriebsdaten-store';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';
import { Route, Calculator, Trash2, ArrowRight, Download, Database, AlertTriangle } from 'lucide-react';
import { toast } from 'sonner';
import { computeAllPaths, pathResultToPath, buildGangGraph, findPath } from '@/lib/pathfinding';
import { berechneVerteilwegAusDistanzmatrix } from '@/lib/distanzmatrix-rechner';
import { SCHMID_DISTANZMATRIX } from '@/lib/data/schmid-distanzmatrix';
import type { PathResult } from '@/lib/pathfinding';
import type { TopisObject, Path } from '@/types/topis';
import type { Distanzmatrix } from '@/types/distanzmatrix';

interface WegeResult {
  start: TopisObject;
  end: TopisObject;
  result: PathResult | null;
  distEuclidean: number;
}

const byName = (a: { name?: string }, b: { name?: string }) =>
  (a.name || '').localeCompare(b.name || '', 'de', { numeric: true });

export function WegeberechnungDialog() {
  const [isOpen, setIsOpen] = useState(false);
  const [selectedFFZId, setSelectedFFZId] = useState<string>('');
  const [selectedStart, setSelectedStart] = useState<Set<number>>(new Set());
  const [selectedEnd, setSelectedEnd] = useState<Set<number>>(new Set());
  const [results, setResults] = useState<WegeResult[]>([]);
  const [runName, setRunName] = useState<string>('');
  const [runProzess, setRunProzess] = useState<string>('');
  const [isCalculating, setIsCalculating] = useState(false);
  const [verteilweg, setVerteilweg] = useState<number | null>(null);
  const [wegeCoverage, setWegeCoverage] = useState<number>(1); // Anteil echter Wege (Belastbarkeit)
  const [selectedDM, setSelectedDM] = useState<string>('');
  const [dmErgebnis, setDmErgebnis] = useState<{ gewichteterWegM: number; gesamtColli: number; abgedeckteColli: number; nichtZugeordnet: number } | null>(null);

  const setDistanzmatrix = useBetriebsdatenStore((s) => s.setDistanzmatrix);
  const setDistanzmatrixErgebnis = useBetriebsdatenStore((s) => s.setDistanzmatrixErgebnis);

  const objects = useTopisStore((s) => s.objects);
  const gaenge = useTopisStore((s) => s.gaenge);
  const pathAreas = useTopisStore((s) => s.pathAreas);
  const pathsAll = useTopisStore((s) => s.paths);
  const ffzList = useTopisStore((s) => s.ffz);
  const addPaths = useTopisStore((s) => s.addPaths);
  const deleteAutoGeneratedPaths = useTopisStore((s) => s.deleteAutoGeneratedPaths);
  const autoPathCount = useTopisStore((s) => s.paths.filter(p => p.autoGenerated).length);
  const saveMittlererWegRun = useTopisStore((s) => s.saveMittlererWegRun);
  const mittlereWegRuns = useTopisStore((s) => s.mittlereWegRuns);

  const setVerteilwegProzessmodell = useProzessmodellStore((s) => s.setVerteilweg);

  // Get scan data if available
  const scandatenRecords = useBetriebsdatenStore((s) => s.scandatenRecords);
  const torZuordnungen = useBetriebsdatenStore((s) => s.torZuordnungen);
  const relationZuordnungen = useBetriebsdatenStore((s) => s.relationZuordnungen);
  const hasScanData = scandatenRecords.length > 0;

  // Filter objects by type + Wegpunkt-Rolle, natürlich sortiert (Tor 1, Tor 2, … Tor 115)
  const tore = useMemo(() =>
    objects.filter(o => o.type === 'tor' && (o.wegpunktRolle ?? 'beides') !== 'keiner' && (o.wegpunktRolle ?? 'beides') !== 'ende').sort(byName),
    [objects]
  );
  const stellplaetze = useMemo(() =>
    objects.filter(o => (o.type === 'stellplatz' || o.type === 'bereich') && (o.wegpunktRolle ?? 'beides') !== 'keiner' && (o.wegpunktRolle ?? 'beides') !== 'start').sort(byName),
    [objects]
  );

  const handleOpenChange = (open: boolean) => {
    if (open) {
      setSelectedStart(new Set(tore.map(t => t.id)));
      setSelectedEnd(new Set(stellplaetze.map(s => s.id)));
      setResults([]);
      setVerteilweg(null);
      if (ffzList.length > 0) setSelectedFFZId(String(ffzList[0].id));
    }
    setIsOpen(open);
  };

  const toggleSet = (set: Set<number>, setFn: (s: Set<number>) => void, id: number) => {
    const newSet = new Set(set);
    if (newSet.has(id)) newSet.delete(id);
    else newSet.add(id);
    setFn(newSet);
  };

  const calculatePaths = () => {
    setIsCalculating(true);

    const ffz = ffzList.find(f => f.id === Number(selectedFFZId));
    const startObjs = objects.filter(o => selectedStart.has(o.id));
    const endObjs = objects.filter(o => selectedEnd.has(o.id));

    const walls = objects.filter(o => {
      if (o.istUndurchlaessig === false) return false;
      if (o.istUndurchlaessig === true) return true;
      if (o.type === 'tuer') return true;
      return o.type === 'wand' || o.type === 'bereich' || o.type === 'regal' || o.type === 'hindernis';
    });

    // FFZ-Mindestbreiten-Vorabcheck — sonst rechnet A* leer und alle ⚠
    if (ffz) {
      const passable = gaenge.filter(g => g.breite >= ffz.mindestBreite);
      if (gaenge.length > 0 && passable.length === 0) {
        setIsCalculating(false);
        toast.error(
          `Kein Gang ist breit genug für ${ffz.name} (min. ${ffz.mindestBreite} m). Wählen Sie ein schmaleres FFZ oder verbreitern Sie die Gänge.`,
          { duration: 6000 },
        );
        return;
      }
      if (passable.length < gaenge.length) {
        toast.warning(
          `${gaenge.length - passable.length} von ${gaenge.length} Gängen sind schmaler als ${ffz.mindestBreite} m und werden für ${ffz.name} ignoriert.`,
          { duration: 5000 },
        );
      }
    }

    let computed = computeAllPaths(startObjs, endObjs, gaenge, ffz, walls, pathAreas);
    let withPath = computed.filter(c => c.result !== null).length;
    let pathAreaHinweis = '';
    // Wegflächen-Mismatch: decken die (evtl. veralteten) Wegflächen das aktuelle Gangnetz
    // nicht ab, zerschneidet der Filter den Graphen. Statt still fast alle Wege zu verlieren,
    // ohne Wegflächen-Beschränkung neu rechnen und das LAUT melden.
    if (pathAreas.length > 0 && withPath < computed.length * 0.5) {
      const ohne = computeAllPaths(startObjs, endObjs, gaenge, ffz, walls, []);
      const withPathOhne = ohne.filter(c => c.result !== null).length;
      if (withPathOhne > withPath) {
        computed = ohne;
        withPath = withPathOhne;
        pathAreaHinweis = ' Die hinterlegten Wegflächen decken das aktuelle Gangnetz nicht ab — daher ohne Wegflächen-Beschränkung berechnet.';
      }
    }

    const wegeResults: WegeResult[] = computed.map(({ start, end, result }) => {
      const dx = (end.x + end.width / 2) - (start.x + start.width / 2);
      const dy = (end.y + end.height / 2) - (start.y + start.height / 2);
      return { start, end, result, distEuclidean: Math.sqrt(dx * dx + dy * dy) };
    });

    setResults(wegeResults);
    setIsCalculating(false);

    // Verteilweg AUSSCHLIESSLICH aus echten Wegen — NIE Luftlinie einmischen (sonst
    // Fantasiewert). Belastbarkeit = Anteil echter Wege.
    const realDists = wegeResults.filter(r => r.result !== null).map(r => r.result!.distance).filter(d => d > 0);
    const coverage = wegeResults.length > 0 ? withPath / wegeResults.length : 0;
    setWegeCoverage(coverage);
    if (realDists.length > 0) {
      setVerteilweg(realDists.reduce((a, b) => a + b, 0) / realDists.length);
    } else {
      setVerteilweg(0);
    }

    if (coverage < 0.8) {
      toast.warning(
        `Nur ${withPath} von ${wegeResults.length} Verbindungen ergeben einen echten Weg — der Verteilweg ist damit nicht belastbar.${pathAreaHinweis}`,
        { duration: 8000 },
      );
    } else {
      toast.success(`${wegeResults.length} Verbindungen berechnet (${withPath} mit Pfad).${pathAreaHinweis}`);
    }
  };

  const calculateWeightedVerteilweg = () => {
    if (!hasScanData || torZuordnungen.length === 0) {
      toast.error('Keine Scandaten oder Tor-Zuordnungen vorhanden');
      return;
    }

    const ffz = ffzList.find(f => f.id === Number(selectedFFZId));
    const graph = buildGangGraph(gaenge, ffz);

    let totalDistColli = 0;
    let totalColli = 0;   // Colli mit ECHTEM Weg (fließen in den gewichteten Verteilweg)
    let fallbackColli = 0; // Colli ohne echten Weg (kein Ziel/kein Pfad) — NICHT einrechnen, nur zählen

    // Group scan records by stellplatz → tor → relation → target
    const stellplatzGroups = new Map<string, typeof scandatenRecords>();
    scandatenRecords.forEach(r => {
      if (!r.stellplatz) return;
      if (!stellplatzGroups.has(r.stellplatz)) stellplatzGroups.set(r.stellplatz, []);
      stellplatzGroups.get(r.stellplatz)!.push(r);
    });

    stellplatzGroups.forEach((recs, stellplatzKey) => {
      const torZuordnung = torZuordnungen.find(z => z.stellplatzKey === stellplatzKey);
      const torObj = torZuordnung?.objectId ? objects.find(o => o.id === torZuordnung.objectId) : undefined;

      const relationGroups = new Map<string, number>();
      recs.forEach(r => {
        const rel = r.ausgangsrelation || 'UNBEKANNT';
        relationGroups.set(rel, (relationGroups.get(rel) || 0) + r.colli);
      });

      relationGroups.forEach((colli, relation) => {
        const relZuordnung = relationZuordnungen.find(z => z.relationKey === relation);
        const zielObj = relZuordnung?.objectId ? objects.find(o => o.id === relZuordnung.objectId) : undefined;
        let distanzM: number | null = null;

        if (torObj && zielObj) {
          const fromCenter = { x: torObj.x + torObj.width / 2, y: torObj.y + torObj.height / 2 };
          const toCenter = { x: zielObj.x + zielObj.width / 2, y: zielObj.y + zielObj.height / 2 };
          const pathResult = findPath(fromCenter.x, fromCenter.y, toCenter.x, toCenter.y, graph, ffz);
          if (pathResult) distanzM = pathResult.distance; // NUR echter Weg, keine Luftlinie/Magic-50
        }

        if (distanzM != null && distanzM > 0) {
          totalDistColli += distanzM * colli;
          totalColli += colli;
        } else {
          fallbackColli += colli; // kein echter Weg → NICHT als 50 m/Luftlinie fabrizieren
        }
      });
    });

    if (totalColli > 0) {
      const gewVerteilweg = totalDistColli / totalColli;
      const abdeckung = totalColli / (totalColli + fallbackColli);
      setVerteilweg(gewVerteilweg);
      setWegeCoverage(abdeckung);
      if (abdeckung < 0.8) {
        toast.warning(`Gewichteter Verteilweg ${gewVerteilweg.toFixed(1)} m aus nur ${Math.round(abdeckung * 100)} % der Colli (${fallbackColli} Colli ohne echten Weg blieben unberücksichtigt) — nicht belastbar.`, { duration: 8000 });
      } else {
        toast.success(`Gewichteter Verteilweg: ${gewVerteilweg.toFixed(1)} m (${totalColli} Colli mit echtem Weg)`);
      }
    } else {
      setVerteilweg(0);
      setWegeCoverage(0);
      toast.error('Kein belastbarer Verteilweg: keine einzige Relation hat einen echten Weg (Tor-/Relations-Zuordnungen + Gangnetz prüfen).');
    }
  };

  const handleAddToLayout = () => {
    const pathsToAdd: Omit<Path, 'id'>[] = results
      .filter(r => r.result !== null)
      .map(r => pathResultToPath(r.result!, r.start, r.end));

    if (pathsToAdd.length === 0) {
      toast.error('Keine berechneten Pfade zum Hinzufügen');
      return;
    }

    addPaths(pathsToAdd);
    toast.success(`${pathsToAdd.length} Wege ins Layout übernommen`);
  };

  const handleDeleteAuto = () => {
    deleteAutoGeneratedPaths();
    toast.success('Auto-generierte Wege gelöscht');
  };

  /** Lastenheft 3.2.4: Run mit Name + Prozess speichern, wiederholbar */
  const handleSaveRun = () => {
    if (results.length === 0) {
      toast.error('Erst Wege berechnen');
      return;
    }
    const name = runName.trim() || `Mittlerer Weg ${new Date().toLocaleString('de-DE')}`;
    saveMittlererWegRun({
      name,
      prozess: runProzess.trim() || undefined,
      timestamp: new Date().toISOString(),
      startIds: Array.from(selectedStart),
      endIds: Array.from(selectedEnd),
      ffzId: selectedFFZId ? Number(selectedFFZId) : undefined,
      ergebnisVerteilweg: verteilweg ?? undefined,
      ergebnisAnzahl: results.filter(r => r.result !== null).length,
    });
    toast.success(`Run "${name}" gespeichert`);
    setRunName('');
    setRunProzess('');
  };

  /** Lastenheft 3.2.4.4: CSV-Export Art|Start|Ende|Weg|Länge. Auto-Wege zuerst,
   * manuelle Wege (für die gleiche Start/End-Kombi gefunden) danach. */
  const handleCsvExport = () => {
    if (results.length === 0) {
      toast.error('Erst Wege berechnen, dann exportieren');
      return;
    }
    const lines: string[] = ['Art;Start;Ende;Weg;Länge[m];Zeit[s]'];
    // Auto-Wege (A)
    for (const r of results) {
      const name = `${r.start.name}-${r.end.name}`;
      if (r.result) {
        lines.push(`A;${r.start.name};${r.end.name};${name};${r.result.distance.toFixed(1)};${r.result.time.toFixed(1)}`);
      } else {
        lines.push(`A;${r.start.name};${r.end.name};${name};—;—`);
      }
    }
    // Manuelle Wege (M) — gegen die gleichen Start/End-Kombis prüfen
    const manualPaths = pathsAll.filter(p => !p.autoGenerated && p.startObjectId != null && p.endObjectId != null);
    for (const r of results) {
      const matches = manualPaths.filter(p => p.startObjectId === r.start.id && p.endObjectId === r.end.id);
      for (const p of matches) {
        const lenM = p.distance ?? p.waypoints.reduce((sum, w, i) => i === 0 ? 0 : sum + Math.hypot(w.x - p.waypoints[i-1].x, w.y - p.waypoints[i-1].y), 0);
        const timeS = p.time ?? 0;
        lines.push(`M;${r.start.name};${r.end.name};${p.name};${lenM.toFixed(1)};${timeS.toFixed(1)}`);
      }
    }
    const csv = lines.join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `wegberechnung_${new Date().toISOString().slice(0,10)}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success(`CSV exportiert (${lines.length - 1} Zeilen)`);
  };

  const handleVerteilwegUebernehmen = () => {
    if (verteilweg === null || verteilweg <= 0) {
      toast.error('Kein belastbarer Verteilweg vorhanden — es wurden keine echten Wege gefunden.');
      return;
    }
    if (wegeCoverage < 0.8) {
      toast.error(`Verteilweg nicht belastbar (nur ${Math.round(wegeCoverage * 100)} % der Verbindungen haben einen echten Weg) — bitte erst das Gangnetz vervollständigen.`);
      return;
    }
    setVerteilwegProzessmodell(verteilweg);
    // Ehrlich: das native Cockpit-Modell liest diesen Store NICHT automatisch.
    toast.success(`Verteilweg ${verteilweg.toFixed(1)} m gespeichert. Im Cockpit erscheint eine Übernehmen-Brücke, sobald dort ein Prozessmodell mit Verteilweg-Schritt geladen ist.`, { duration: 7000 });
  };

  // Statistics — Ø/Max/Min NUR aus echten Wegen (nie Luftlinie einmischen).
  const stats = useMemo(() => {
    if (results.length === 0) return null;
    const realDistances = results.filter(r => r.result !== null).map(r => r.result!.distance);
    const withPath = realDistances.length;
    return {
      count: results.length,
      withPath,
      avgDist: withPath > 0 ? realDistances.reduce((a, b) => a + b, 0) / withPath : null,
      maxDist: withPath > 0 ? Math.max(...realDistances) : null,
      minDist: withPath > 0 ? Math.min(...realDistances) : null,
    };
  }, [results]);

  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm" className="gap-1.5 h-8">
          <Route className="h-3.5 w-3.5" />
          <span className="hidden lg:inline">Wege</span>
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-5xl max-h-[90vh]">
        <DialogHeader>
          <DialogTitle>Automatische Wegeberechnung</DialogTitle>
          <DialogDescription>
            Berechne kürzeste Wege zwischen Toren und Stellplätzen über das Gang-Netzwerk.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* FFZ Selection */}
          <div className="flex items-center gap-4">
            <div className="w-64">
              <Label className="text-sm font-medium">Flurförderzeug</Label>
              <Select value={selectedFFZId} onValueChange={setSelectedFFZId}>
                <SelectTrigger className="mt-1">
                  <SelectValue placeholder="FFZ auswählen" />
                </SelectTrigger>
                <SelectContent>
                  {ffzList.map(f => (
                    <SelectItem key={f.id} value={String(f.id)}>
                      {f.name} ({f.geschwindigkeit} km/h, min. {f.mindestBreite}m)
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            {gaenge.length === 0 && (
              <Badge variant="destructive" className="mt-5">Keine Gänge vorhanden</Badge>
            )}
          </div>

          {/* Start / End Selection */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <div className="flex items-center justify-between mb-2">
                <Label className="font-medium">Startpunkte (Tore: {tore.length})</Label>
                <div className="space-x-1">
                  <Button variant="ghost" size="sm" onClick={() => setSelectedStart(new Set(tore.map(t => t.id)))}>Alle</Button>
                  <Button variant="ghost" size="sm" onClick={() => setSelectedStart(new Set())}>Keine</Button>
                </div>
              </div>
              <ScrollArea className="h-40 border rounded-md p-2">
                {tore.map(t => (
                  <div key={t.id} className="flex items-center space-x-2 py-0.5">
                    <Checkbox
                      id={`ws-${t.id}`}
                      checked={selectedStart.has(t.id)}
                      onCheckedChange={() => toggleSet(selectedStart, setSelectedStart, t.id)}
                    />
                    <label htmlFor={`ws-${t.id}`} className="text-sm cursor-pointer">{t.name}</label>
                  </div>
                ))}
                {tore.length === 0 && <p className="text-sm text-muted-foreground p-2">Keine Tore vorhanden</p>}
              </ScrollArea>
            </div>
            <div>
              <div className="flex items-center justify-between mb-2">
                <Label className="font-medium">Endpunkte (Stellplätze/Bereiche: {stellplaetze.length})</Label>
                <div className="space-x-1">
                  <Button variant="ghost" size="sm" onClick={() => setSelectedEnd(new Set(stellplaetze.map(s => s.id)))}>Alle</Button>
                  <Button variant="ghost" size="sm" onClick={() => setSelectedEnd(new Set())}>Keine</Button>
                </div>
              </div>
              <ScrollArea className="h-40 border rounded-md p-2">
                {stellplaetze.map(s => (
                  <div key={s.id} className="flex items-center space-x-2 py-0.5">
                    <Checkbox
                      id={`we-${s.id}`}
                      checked={selectedEnd.has(s.id)}
                      onCheckedChange={() => toggleSet(selectedEnd, setSelectedEnd, s.id)}
                    />
                    <label htmlFor={`we-${s.id}`} className="text-sm cursor-pointer">
                      {s.name} <span className="text-muted-foreground text-xs">({s.type})</span>
                    </label>
                  </div>
                ))}
                {stellplaetze.length === 0 && <p className="text-sm text-muted-foreground p-2">Keine Stellplätze/Bereiche vorhanden</p>}
              </ScrollArea>
            </div>
          </div>

          {/* Calculate Button */}
          <div className="flex gap-2">
            <Button
              onClick={calculatePaths}
              disabled={isCalculating || selectedStart.size === 0 || selectedEnd.size === 0 || gaenge.length === 0}
            >
              <Calculator className="h-4 w-4 mr-2" />
              {isCalculating ? 'Berechne...' : `Wege berechnen (${selectedStart.size} × ${selectedEnd.size})`}
            </Button>
          </div>

          {/* Results */}
          {results.length > 0 && (
            <>
              <Separator />

              {/* Stats */}
              {stats && (
                <div className="grid grid-cols-5 gap-2 text-sm bg-muted/50 p-3 rounded-lg">
                  <div>
                    <div className="text-muted-foreground">Anzahl</div>
                    <div className="font-medium">{stats.count}</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Mit Pfad</div>
                    <div className={`font-medium ${stats.withPath < stats.count ? 'text-amber-600 dark:text-amber-500' : ''}`}>{stats.withPath}/{stats.count}</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Ø Distanz{stats.withPath < stats.count ? ' (nur echte Wege)' : ''}</div>
                    <div className="font-medium">{stats.avgDist != null ? `${stats.avgDist.toFixed(1)} m` : '—'}</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Min</div>
                    <div className="font-medium">{stats.minDist != null ? `${stats.minDist.toFixed(1)} m` : '—'}</div>
                  </div>
                  <div>
                    <div className="text-muted-foreground">Max</div>
                    <div className="font-medium">{stats.maxDist != null ? `${stats.maxDist.toFixed(1)} m` : '—'}</div>
                  </div>
                </div>
              )}

              {/* Results Table */}
              <ScrollArea className="h-48 border rounded-md">
                <table className="w-full text-sm">
                  <thead className="bg-muted sticky top-0">
                    <tr>
                      <th className="p-2 text-left">Von</th>
                      <th className="p-2 text-left">Nach</th>
                      <th className="p-2 text-right">Distanz (m)</th>
                      <th className="p-2 text-right">Zeit (s)</th>
                      <th className="p-2 text-center">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {results.map((r, i) => (
                      <tr key={i} className="border-t">
                        <td className="p-2">{r.start.name}</td>
                        <td className="p-2">{r.end.name}</td>
                        <td className="p-2 text-right">
                          {r.result ? r.result.distance.toFixed(1) : r.distEuclidean.toFixed(1)}
                        </td>
                        <td className="p-2 text-right">
                          {r.result ? r.result.time.toFixed(1) : '-'}
                        </td>
                        <td className="p-2 text-center">{r.result ? '✓' : '⚠'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </ScrollArea>

              {/* Action Buttons */}
              <div className="flex gap-2 flex-wrap">
                <Button onClick={handleAddToLayout} variant="default">
                  <ArrowRight className="h-4 w-4 mr-2" />
                  Wege in Layout übernehmen ({results.filter(r => r.result).length})
                </Button>
                <Button onClick={handleCsvExport} variant="outline">
                  CSV-Export
                </Button>
                {autoPathCount > 0 && (
                  <Button onClick={handleDeleteAuto} variant="outline" className="text-destructive">
                    <Trash2 className="h-4 w-4 mr-2" />
                    Auto-Wege löschen ({autoPathCount})
                  </Button>
                )}
              </div>

              <Separator />

              {/* Mittlerer-Weg-Run speichern */}
              <div className="space-y-2">
                <h4 className="font-medium text-sm">Mittlerer-Weg-Run speichern</h4>
                <div className="grid grid-cols-[1fr_1fr_auto] gap-2 items-end">
                  <div className="space-y-1">
                    <Label className="text-xs">Bezeichnung</Label>
                    <Input value={runName} onChange={(e) => setRunName(e.target.value)} placeholder="z.B. SE Februar 2026" />
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs">Prozess (optional)</Label>
                    <Input value={runProzess} onChange={(e) => setRunProzess(e.target.value)} placeholder="z.B. SE Entladung" />
                  </div>
                  <Button onClick={handleSaveRun} variant="secondary">Run speichern</Button>
                </div>
                {mittlereWegRuns.length > 0 && (
                  <div className="text-xs text-muted-foreground space-y-0.5 max-h-32 overflow-auto border rounded p-2">
                    <div className="font-medium">Gespeicherte Runs ({mittlereWegRuns.length}):</div>
                    {mittlereWegRuns.slice().reverse().map(r => (
                      <div key={r.id}>
                        • {r.name}{r.prozess ? ` (${r.prozess})` : ''} — {r.ergebnisAnzahl ?? '?'} Wege
                        {r.ergebnisVerteilweg != null && `, Ø ${r.ergebnisVerteilweg.toFixed(1)} m`}
                        {' '}<span className="opacity-60">{new Date(r.timestamp).toLocaleString('de-DE')}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              <Separator />

              {/* Verteilweg Section */}
              <div className="space-y-3">
                <h4 className="font-medium text-sm">Verteilweg (aus Layout-Berechnung)</h4>
                <div className="flex gap-2 items-center flex-wrap">
                  {hasScanData ? (
                    <Button onClick={calculateWeightedVerteilweg} variant="outline" size="sm">
                      <Calculator className="h-4 w-4 mr-2" />
                      Gewichteten Verteilweg berechnen (Scandaten)
                    </Button>
                  ) : (
                    <p className="text-sm text-muted-foreground">
                      Ohne Scandaten: Ungewichteter Durchschnitt aller Distanzen.
                      Importiere Betriebsdaten für Colli-gewichteten Verteilweg.
                    </p>
                  )}
                </div>
                {verteilweg !== null && verteilweg > 0 && (
                  <div className="flex items-center gap-4 bg-muted/50 p-3 rounded-lg">
                    <div>
                      <div className="text-muted-foreground text-xs">
                        {hasScanData ? 'Gewichteter Verteilweg' : 'Ø Verteilweg (ungewichtet, nur echte Wege)'}
                      </div>
                      <div className="text-xl font-bold">{verteilweg.toFixed(1)} m</div>
                    </div>
                    <Button onClick={handleVerteilwegUebernehmen} size="sm" disabled={wegeCoverage < 0.8}>
                      <ArrowRight className="h-4 w-4 mr-2" />
                      Ins Prozessmodell übernehmen
                    </Button>
                  </div>
                )}
                {wegeCoverage < 0.8 && verteilweg !== null && verteilweg > 0 && (
                  <div className="flex items-start gap-2 text-amber-600 dark:text-amber-500 text-sm mt-1">
                    <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />
                    <span>Nur {Math.round(wegeCoverage * 100)} % der Verbindungen haben einen echten Weg — der Verteilweg ist nicht belastbar. Gangnetz/Wegflächen prüfen, bevor du übernimmst.</span>
                  </div>
                )}
              </div>

              <Separator />

              {/* Gemessene Distanzmatrix Section */}
              <div className="space-y-3">
                <h4 className="font-medium text-sm flex items-center gap-2">
                  <Database className="h-4 w-4" />
                  Gemessene Distanzmatrix
                </h4>
                <p className="text-xs text-muted-foreground">
                  Echte Messwerte statt A*-Berechnung. Distanzen aus physischen Messungen in der Halle.
                </p>
                <div className="flex items-center gap-2">
                  <Select value={selectedDM} onValueChange={setSelectedDM}>
                    <SelectTrigger className="w-64">
                      <SelectValue placeholder="Distanzmatrix auswählen..." />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="schmid_halle6">Demo-Distanzmatrix (204 Paare, 82.120 Colli)</SelectItem>
                    </SelectContent>
                  </Select>
                  <Button
                    onClick={() => {
                      if (selectedDM === 'schmid_halle6') {
                        const erg = berechneVerteilwegAusDistanzmatrix(SCHMID_DISTANZMATRIX);
                        setDmErgebnis(erg);
                        setDistanzmatrix(SCHMID_DISTANZMATRIX);
                        setDistanzmatrixErgebnis(erg);
                        toast.success(`Gemessener Verteilweg: ${erg.gewichteterWegM.toFixed(1)}m`);
                      }
                    }}
                    disabled={!selectedDM}
                    variant="outline"
                    size="sm"
                  >
                    <Calculator className="h-4 w-4 mr-2" />
                    Verteilweg aus Messungen berechnen
                  </Button>
                </div>

                {dmErgebnis && (
                  <div className="space-y-2">
                    <div className="bg-muted/50 p-3 rounded-lg space-y-2">
                      <div className="grid grid-cols-4 gap-3 text-sm">
                        <div>
                          <div className="text-muted-foreground text-xs">Gemessener Verteilweg</div>
                          <div className="text-xl font-bold text-primary">{dmErgebnis.gewichteterWegM.toFixed(1)} m</div>
                        </div>
                        <div>
                          <div className="text-muted-foreground text-xs">Abgedeckte Colli</div>
                          <div className="font-medium">{dmErgebnis.abgedeckteColli.toLocaleString()}</div>
                        </div>
                        <div>
                          <div className="text-muted-foreground text-xs">Gesamt Colli</div>
                          <div className="font-medium">{dmErgebnis.gesamtColli.toLocaleString()}</div>
                        </div>
                        <div>
                          <div className="text-muted-foreground text-xs">Nicht zugeordnet</div>
                          <div className="font-medium">{dmErgebnis.nichtZugeordnet.toLocaleString()}</div>
                        </div>
                      </div>

                      {/* Vergleich */}
                      {verteilweg !== null && (
                        <div className="flex items-center gap-2 text-sm border-t pt-2">
                          <span className="text-muted-foreground">Vergleich:</span>
                          <Badge variant="outline">Berechnet: {verteilweg.toFixed(1)}m</Badge>
                          <span className="text-muted-foreground">|</span>
                          <Badge variant="default">Gemessen: {dmErgebnis.gewichteterWegM.toFixed(1)}m</Badge>
                          <span className="text-muted-foreground">|</span>
                          <Badge variant={Math.abs(dmErgebnis.gewichteterWegM - verteilweg) / verteilweg > 0.15 ? 'destructive' : 'secondary'}>
                            {((dmErgebnis.gewichteterWegM - verteilweg) / verteilweg * 100) > 0 ? '+' : ''}
                            {((dmErgebnis.gewichteterWegM - verteilweg) / verteilweg * 100).toFixed(1)}%
                          </Badge>
                        </div>
                      )}
                    </div>
                    <Button
                      onClick={() => {
                        setVerteilwegProzessmodell(dmErgebnis.gewichteterWegM);
                        toast.success(`Gemessener Verteilweg ${dmErgebnis.gewichteterWegM.toFixed(1)}m ins Prozessmodell übernommen`);
                      }}
                      size="sm"
                    >
                      <ArrowRight className="h-4 w-4 mr-2" />
                      Gemessenen Verteilweg ins Prozessmodell übernehmen
                    </Button>
                  </div>
                )}
              </div>
            </>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => setIsOpen(false)}>
            Schließen
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
